name: Deploy CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ci-cd/**'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init
        working-directory: ./ci-cd

      - name: Terraform Apply
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          terraform apply -auto-approve -var='artifact_bucket_name=${{ vars.ARTIFACT_BUCKET_NAME }}'
        working-directory: ./ci-cd
